version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend                    # теперь указываем папку backend
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - REDIS_HOST=redis
      - ALLOWED_ORIGINS=["http://localhost:3000"]
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - redis
    volumes:
      - ./backend/app:/app/app           # монтируем код из backend/app

volumes:
  es_data: